 version: "3"
 services:
  
  mysql-user:
    container_name: "mysql-user"
    image: mysql
    hostname: localhost
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=Root@123
     - MYSQLDB_USER=root
     - MYSQL_DATABASE=project
     - MYSQL_PASSWORD=Root@123
  
  rabbitmq-container:
      image: rabbitmq:3-management
      ports:
        - 5672:5672
        - 15672:15672
  
  notification-service:
    build: .
   # container_name: notification-service
    network_mode: host
    hostname: localhost
    restart: always
   # ports:
    #  - 8092:8092
    depends_on:
      - mysql-user
      - rabbitmq-container
    
   