 version: "3"
 services:
  order-service:
    build: .
    container_name: orderservice
    restart: always
    network_mode: "host"
    hostname: localhost
  
      
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    hostname: localhost
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672


    